public enum AIComponents
{ 
	AIMovement_TowardsPlayer,
	AIMovement_TowardsCube,
	AIMovement_TowardsCenter,
	AIMovement_Temporize,
	AIMovement_Away,
	AIDash_Hit,
	AIDash_Towards,
	AIDash_Dodge,
	AIDash_Counter,
	AIAimForwards,
	AIAimPlayer,
	AIAimCube,
	AIShoot,
	AIAttract,
	AIRepel,
	AIStuck,
	AIDash_Away,
	AIMovement_Towards_Pool
};